baseURL: "https://ic.atr.rio.br"
title: "Site do IC"
theme: temaic

taxonomies:
  author: autores

defaultContentLanguage: pt
defaultContentLanguageInSubdir: false
languages:
  pt:
    languageName: Português
    languageCode: "pt-BR"
    contentDir: content/pt
    weight: 1
  en:
    languageName: English
    languageCode: en
    contentDir: content/en
    weight: 2


