baseURL: "https://ic.atr.rio.br"
title: "Site do IC"
theme: temaic

taxonomies:
  author: authors

defaultContentLanguage: "pt-BR"
defaultContentLanguageInSubdir: false
languages:
  pt-BR:
    languageName: "Português"
    weight: 1
  en:
    languageName: "English"
    weight: 2


